import type { Metadata } from "next";
import { Poppins } from "next/font/google"; // Importing Poppins from Google Fonts
import "./globals.css";
import { Header } from "@/layout/Header";
import { Footer } from "@/layout/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // Adjust weights as needed
});

export const metadata: Metadata = {
  title: "Hi Acuity",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased overflow-x-hidden`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
